In [36]:
import numpy as np


In [37]:
#creating single dimension arrays
a=np.array([1,2,3,4,5])

In [38]:
#another onedimension array
b=np.array([32,22,45,4764,5,4])

In [39]:
a


array([1, 2, 3, 4, 5])

In [40]:
b

array([  32,   22,   45, 4764,    5,    4])

In [41]:
b
a

array([1, 2, 3, 4, 5])

In [42]:
a,b

(array([1, 2, 3, 4, 5]), array([  32,   22,   45, 4764,    5,    4]))

In [43]:
#2D array
x=np.array([[2,3,1],[3,4,3],[3,45,4],[23,3,3]])

In [44]:
x

array([[ 2,  3,  1],
       [ 3,  4,  3],
       [ 3, 45,  4],
       [23,  3,  3]])

In [45]:
x[3]

array([23,  3,  3])

In [46]:
x[1][2] #first row ka 3rd element

3

In [47]:
x[1:3]

array([[ 3,  4,  3],
       [ 3, 45,  4]])

In [48]:
x

array([[ 2,  3,  1],
       [ 3,  4,  3],
       [ 3, 45,  4],
       [23,  3,  3]])

In [49]:
x+9

array([[11, 12, 10],
       [12, 13, 12],
       [12, 54, 13],
       [32, 12, 12]])

In [50]:
x**3

array([[    8,    27,     1],
       [   27,    64,    27],
       [   27, 91125,    64],
       [12167,    27,    27]])

In [51]:
print(x[1][2],x[3][2])

3 3


In [52]:
print('jj',end='\n')
print('hh')

jj
hh


In [53]:
x.shape

(4, 3)

In [54]:
y=x.reshape(3,4)

In [55]:
y

array([[ 2,  3,  1,  3],
       [ 4,  3,  3, 45],
       [ 4, 23,  3,  3]])

In [56]:
y[1]

array([ 4,  3,  3, 45])

In [57]:
y[1:,3]

array([45,  3])

In [58]:
y[:,3:]

array([[ 3],
       [45],
       [ 3]])

In [59]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [61]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [62]:
np.ones((6,7), dtype='int32')

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)

In [63]:
x1=x*3

In [64]:
x1

array([[  6,   9,   3],
       [  9,  12,   9],
       [  9, 135,  12],
       [ 69,   9,   9]])

In [65]:
x+x1

array([[  8,  12,   4],
       [ 12,  16,  12],
       [ 12, 180,  16],
       [ 92,  12,  12]])

In [66]:
np.add(x,x1)

array([[  8,  12,   4],
       [ 12,  16,  12],
       [ 12, 180,  16],
       [ 92,  12,  12]])

In [67]:
x/2

array([[ 1. ,  1.5,  0.5],
       [ 1.5,  2. ,  1.5],
       [ 1.5, 22.5,  2. ],
       [11.5,  1.5,  1.5]])

In [68]:
(x+x1)/2

array([[ 4.,  6.,  2.],
       [ 6.,  8.,  6.],
       [ 6., 90.,  8.],
       [46.,  6.,  6.]])

In [69]:
(np.add(x,x1))/4

array([[ 2.,  3.,  1.],
       [ 3.,  4.,  3.],
       [ 3., 45.,  4.],
       [23.,  3.,  3.]])

In [71]:
x

array([[ 2,  3,  1],
       [ 3,  4,  3],
       [ 3, 45,  4],
       [23,  3,  3]])

In [ ]:
x